name: Update badges

on:
  schedule:
    - cron: "0 2 * * *"
  # push:
  #   branches: ["main"]

jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest

    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: guilherme-oliveira.54e02c9b

      - name: Fix badges inline layout
        run: |
          # Remove quebras de linha entre as imagens das badges para forçar o layout inline
          sed -i '/<a href="https:\/\/www.credly.com\/badges\// { N; s/\n//; }' README.md
          # Remove espaços excessivos entre as tags de imagem
          sed -i 's/> </></g' README.md
