name: Update badges

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest

    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: guilherme-oliveira.54e02c9b

      - name: Fix badges inline layout
        run: |
          # Remove quebras de linha entre badges
          tr '\n' ' ' < README.md > README.tmp && mv README.tmp README.md

          # Limpa múltiplos espaços
          sed -i 's/[[:space:]]\+/ /g' README.md
